[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 0.8
blur = true
option_as_alt = "both"

[font]
normal.family = "CaskaydiaCove Nerd Font Mono"
size = 16

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"  # Skip word left

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"  # Skip word right

[[keyboard.bindings]]
key = "Back"
mods = "Command"
chars = "\u0015"  # Delete line

# [[keyboard.bindings]]
# key = "Left"
# mods = "Command"
# chars = "\u001bOH"  # Home (Command + Left Arrow)

# [[keyboard.bindings]]
# key = "Right"
# mods = "Command"
# chars = "\u001bOF"  # End (Command + Right Arrow)

